import { getClassName } from './class-generator.js';
import { buildRuleString, buildMediaQueryString } from './css-generator.js';
import { BREAKPOINTS } from '../config.js';

export function exportCSS(editor) {
    const elements = editor.getElements();
    const seen = new Set();
    let css = '/* Generated by HTML Studio */\n\n';

    if (editor.themeManager) {
        css += editor.themeManager.exportThemeCSS();
    }

    css += `*, *::before, *::after {\n    box-sizing: border-box;\n}\n\n`;
    css += `body {\n    margin: 0;\n    padding: 0;\n    font-family: sans-serif;\n}\n\n`;

    elements.forEach(el => {
        if (el.dataset.hidden === 'true') return;

        const className = getClassName(el);
        if (seen.has(className)) return;
        seen.add(className);

        const style = el.style;
        if (style.length === 0) return;

        const skipProps = new Set(['pointer-events']);
        const props = [];
        for (let i = 0; i < style.length; i++) {
            const prop = style[i];
            if (skipProps.has(prop)) continue;
            const value = style.getPropertyValue(prop);
            if (value) props.push(`${prop}: ${value};`);
        }

        if (props.length > 0) {
            css += buildRuleString(className, props) + '\n\n';
        }
    });

    const bpManager = editor.breakpointManager;
    if (bpManager) {
        const breakpointDefs = Object.entries(BREAKPOINTS)
            .filter(([, def]) => def.mediaQuery)
            .map(([bp, def]) => ({ bp, media: def.mediaQuery }));

        breakpointDefs.forEach(({ bp, media }) => {
            const mediaRules = [];

            elements.forEach(el => {
                if (el.dataset.hidden === 'true') return;
                const overrides = bpManager.getOverrides(el);
                const bpOverride = overrides[bp];
                if (!bpOverride || Object.keys(bpOverride).length === 0) return;

                const className = getClassName(el);
                const skipProps = new Set(['pointer-events']);
                const props = Object.entries(bpOverride)
                    .filter(([p]) => !skipProps.has(p))
                    .map(([p, v]) => `${p}: ${v};`);

                if (props.length > 0) {
                    mediaRules.push(buildRuleString(className, props, '        ', '    '));
                }
            });

            if (mediaRules.length > 0) {
                css += buildMediaQueryString(media, mediaRules) + '\n\n';
            }
        });
    }

    return css;
}
